/*
 * generated by Xtext 2.25.0
 */
package org.emoflon.gips.gipsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GipslUiModule extends AbstractGipslUiModule {

	public GipslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
