/*
 * generated by Xtext 2.25.0
 */
package org.emoflon.roam.roamslang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RoamSLangUiModule extends AbstractRoamSLangUiModule {

	public RoamSLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
