/*
 * generated by Xtext 2.25.0
 */
package org.emoflon.roam.roamslang.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.emoflon.roam.roamslang.roamSLang.EditorGTFile
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(RoamSLangInjectorProvider)
class RoamSLangParsingTest {
	@Inject
	ParseHelper<EditorGTFile> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		// TODO: Resolve this access error
//		val errors = result.eResource.errors
//		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testNonEmptyMappings() {
		val result = parseHelper.parse('''
			rule testRule {
				
			}
			mapping map with testRule;
		''')
		Assertions.assertNotNull(result)
		val mappings = result.mappings
		Assertions.assertFalse(mappings.isEmpty)
	}
	
	@Test
	def void testNonEmptyConstraints() {
		val result = parseHelper.parse('''
			rule testRule {
				
			}
			mapping map with testRule;
			constraint -> mapping::map {
				1 != 2
			}
		''')
		Assertions.assertNotNull(result)
		val constraints = result.constraints
		Assertions.assertFalse(constraints.isEmpty)
	}
	
	@Test
	def void testNonEmptyObjectives() {
		val result = parseHelper.parse('''
			rule testRule {
				
			}
			mapping map with testRule;
			objective obj -> mapping::map {
				1
			}
		''')
		Assertions.assertNotNull(result)
		val objectives = result.objectives
		Assertions.assertFalse(objectives.isEmpty)
	}
	
	@Test
	def void testNonEmptyGlobalObjectives() {
		val result = parseHelper.parse('''
			rule testRule {
				
			}
			mapping map with testRule;
			objective obj -> mapping::map {
				1
			}
			global objective : min {
				2 * obj
			}
		''')
		Assertions.assertNotNull(result)
		Assertions.assertNotNull(result.globalObjective)
	}
}
