/*
 * generated by Xtext 2.33.0
 */
package org.emoflon.gips.debugger;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class CplexLpRuntimeModule extends AbstractCplexLpRuntimeModule {

//	Class<? extends IStratumBreakpointSupport> bindIStratumBreakpointSupport() {
//		return StratumBreakpointSupport.class;
//	}
//
//	@Override
//	public Class<? extends org.eclipse.xtext.linking.ILinker> bindILinker() {
//		return LazyLinker.class;
//	}
//
//	@Override
//	public Class<? extends ILinkingService> bindILinkingService() {
//		return CplexLpLinker.class;
//	}

}
