/*
 * generated by Xtext 2.25.0
 */
package org.emoflon.roam.roamslang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.emoflon.roam.roamslang.RoamSLangRuntimeModule;
import org.emoflon.roam.roamslang.RoamSLangStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RoamSLangIdeSetup extends RoamSLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RoamSLangRuntimeModule(), new RoamSLangIdeModule()));
	}
	
}
