/*
 * generated by Xtext 2.25.0
 */
package org.emoflon.roam.roamslang.ide;


/**
 * Use this class to register ide components.
 */
public class RoamSLangIdeModule extends AbstractRoamSLangIdeModule {
}
