/*
 * generated by Xtext 2.33.0
 */
package org.emoflon.gips.eclipse.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class CplexLpScopeProvider extends AbstractCplexLpScopeProvider {

//	@Inject
//	private DynamicVariableDeclarationLocator varResolver;

	@Override
	public IScope getScope(EObject context, EReference reference) {
//		if (context instanceof Variable) {
//			IEObjectDescription description = varResolver.findDeclarationForReference(context, reference);
//			if (description != null)
//				return new SimpleScope(super.getScope(context, reference), Collections.singleton(description));
//		}
		return super.getScope(context, reference);
	}

}
