/*
 * generated by Xtext 2.25.0
 */
package org.emoflon.gips.gipsl.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class GipslProjectInfo extends DefaultProjectInfo {

}
