/*
 * generated by Xtext 2.25.0
 */
package org.emoflon.gips.gipsl.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class GipslWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public GipslWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
