/*
  * generated by Xtext 2.33.0
 */
package org.emoflon.gips.eclipse;

/**
 * Initialization support for running Xtext languages without Equinox extension
 * registry.
 */
public class CplexLpStandaloneSetup extends CplexLpStandaloneSetupGenerated {

	public static void doSetup() {
		new CplexLpStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
