/*
 * generated by Xtext 2.25.0
 */
package org.emoflon.roam.roamslang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RoamSLangStandaloneSetup extends RoamSLangStandaloneSetupGenerated {

	public static void doSetup() {
		new RoamSLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
