/*
 * generated by Xtext 2.33.0
 */
package org.emoflon.gips.debugger.ui.contentassist;

/**
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class CplexLpProposalProvider extends AbstractCplexLpProposalProvider {
}
