/*
 * generated by Xtext 2.33.0
 */
package org.emoflon.gips.debugger.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.emoflon.gips.debugger.CplexLpRuntimeModule;
import org.emoflon.gips.debugger.CplexLpStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CplexLpIdeSetup extends CplexLpStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CplexLpRuntimeModule(), new CplexLpIdeModule()));
	}
	
}
