/*
 * generated by Xtext 2.37.0
 */
package org.emoflon.gips.eclipse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.emoflon.gips.eclipse.ui.editor.CplexLpEditor;
import org.emoflon.gips.eclipse.ui.editor.preferences.ClplexLpPreferences;
import org.emoflon.gips.eclipse.ui.highlight.ClplexLpHighlightingCalculator;
import org.emoflon.gips.eclipse.ui.highlight.ClplexLpHighlightingConfiguration;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CplexLpUiModule extends AbstractCplexLpUiModule {

	public CplexLpUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends org.eclipse.xtext.ui.editor.XtextEditor> bindXtextEditor() {
		return CplexLpEditor.class;
	}

	public Class<? extends org.eclipse.xtext.ui.editor.preferences.LanguageRootPreferencePage> bindLanguageRootPreferencePage() {
		return ClplexLpPreferences.class;
	}

	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return ClplexLpHighlightingConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return ClplexLpHighlightingCalculator.class;
	}
}
