bin.includes = META-INF/,\
               lib/glpk-java-1.12.0.jar,\
               lib/glpk-java-1.12.0-javadoc.jar,\
               lib/cplex-22.1.2.jar,\
               lib/slf4j-api-2.0.18.jar,\
               lib/slf4j-api-2.0.18-javadoc.jar,\
               lib/oshi-core-7.2.1.jar,\
               lib/oshi-core-7.2.1-javadoc.jar,\
               lib/oshi-core-7.2.1-sources.jar,\
               lib/jna-5.17.0.jar,\
               lib/jna-5.17.0-javadoc.jar,\
               lib/jna-5.17.0-sources.jar,\
               lib/jna-platform-5.17.0.jar,\
               lib/jna-platform-5.17.0-javadoc.jar,\
               lib/jna-platform-5.17.0-sources.jar,\
               lib/gurobi-13.0.2.jar,\
               lib/gurobi-javadoc-13.0.2.jar,\
               lib/slf4j-nop-2.0.18.jar,\
               lib/slf4j-nop-2.0.18-javadoc.jar,\
               lib/gson-2.13.1.jar,\
               lib/gson-2.13.1-javadoc.jar,\
               lib/gson-2.13.1-sources.jar,\
               lib/antlr4-runtime-4.9.3.jar,\
               lib/antlr4-runtime-4.9.3-javadoc.jar,\
               lib/antlr4-runtime-4.9.3-sources.jar,\
               lib/oshi-common-7.2.1.jar,\
               lib/oshi-common-7.2.1-javadoc.jar,\
               lib/oshi-common-7.2.1-sources.jar,\
               lib/logicng-2.6.1.jar,\
               lib/logicng-2.6.1-javadoc.jar,\
               lib/logicng-2.6.1-sources.jar,\
               lib/logicng-parser-j8-2.6.1.jar,\
               lib/logicng-parser-j8-2.6.1-javadoc.jar,\
               lib/logicng-parser-j8-2.6.1-sources.jar,\
               lib/ortools-java-9.15.6755.jar,\
               lib/ortools-win32-x86-64-9.15.6755.jar,\
               lib/ortools-linux-x86-64-9.15.6755.jar,\
               lib/protobuf-java-4.35.0.jar,\
               lib/ortools-darwin-aarch64-9.15.6755.jar,\
               lib/ortools-darwin-x86-64-9.15.6755.jar,\
               lib/ortools-linux-aarch64-9.15.6755.jar
