/*
 * generated by Xtext 2.37.0
 */
package org.emoflon.gips.eclipse.ide;

import org.eclipse.xtext.util.Modules2;
import org.emoflon.gips.eclipse.CplexLpRuntimeModule;
import org.emoflon.gips.eclipse.CplexLpStandaloneSetup;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CplexLpIdeSetup extends CplexLpStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CplexLpRuntimeModule(), new CplexLpIdeModule()));
	}

}
