/*
 * generated by Xtext 2.25.0
 */
package org.emoflon.roam.roamslang.ui.wizard;

import org.eclipse.osgi.util.NLS;

public class Messages extends NLS {
	private static final String BUNDLE_NAME = "org.emoflon.roam.roamslang.ui.wizard.messages"; //$NON-NLS-1$

	public static String HelloWorldProject_Label;
	public static String HelloWorldProject_Description;

	static {
		// initialize resource bundle
		NLS.initializeMessages(BUNDLE_NAME, Messages.class);
	}

	private Messages() {
	}
}
