/*
 * generated by Xtext 2.25.0
 */
package org.emoflon.roam.roamslang.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class RoamSLangProjectInfo extends DefaultProjectInfo {

}
